version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile          # можно использовать production-Dockerfile
      target: build                   # берём build-стадию, там есть компиляторы
      args:
        RUBY_VERSION: "3.3.7"
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      DATABASE_URL: "postgres://postgres:secret@db:5432/spree_dev"
      REDIS_URL: "redis://redis:6379/1"
      # SECRET_KEY_BASE не нужен в development
    volumes:
      - .:/rails:cached               # hot-reload кода
      - bundle:/usr/local/bundle      # кэш gem-ов
    ports:
      - "3000:3000"
    depends_on: [db, redis]

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  db_data:
  bundle: